export const mathLinks = [
    { url: "/mathcount", title: "Counting", plaintTitle: "Counting", ex: "1 2 3", css: "card-counter primary"},
    { url: "/mathskipcount", title: "Skip Counting", plaintTitle: "Skip Counting", ex: "2 4 6", css: "card-counter danger"},
    { url: "/mathboxcount", title: "Counting Boxes", plaintTitle: "Counting Boxes", ex: "■ ■ ■", css: "card-counter success" },
    { url: "/mathskipcountextended", title: "Skip Count Extended", plaintTitle: "Skip Count Extended", ex: "2 4 6", css: "card-counter success" },
    { url: "/mathskipcountrule", title: "Skip Count Rule", plaintTitle: "Skip Count Rule", ex: "1   5 7", css: "card-counter primary" },
    { url: "/mathnumbercompare", title: "Comparing Number", plaintTitle: "Comparing Number", ex: "< > =", css: "card-counter danger" },
    { url: "/mathexpandedform", title: "Expanded Form", plaintTitle: "Expanded Form", ex: "100+10+1", css: "card-counter danger" },
    { url: "/mathnumbertowords", title: "Number To Words", plaintTitle: "Number To Words", ex: "one two three", css: "card-counter success" },
    { url: "/mathplacevalue", title: "Place Value", plaintTitle: "Place Value", ex: "ones, tens", css: "card-counter primary" },
    { url: "/mathnumberorder", title: "Number Ordering", plaintTitle: "Number Ordering", ex: "1 2 3 4", css: "card-counter primary" },
    { url: "/mathaddition", title: "Addition (+)", plaintTitle: "Addition", ex: "+", css: "card-counter danger" },
    { url: "/mathsubtraction", title: "Subtraction (&#x2212;)", plaintTitle: "Subtraction", ex: "-", css: "card-counter success" },
    { url: "/mathmultiplication", title: "Multiplication (&#215;)", plaintTitle: "Multiplication", ex: "×", css: "card-counter danger" },
    { url: "/mathdivision", title: "Division (&#xf7;)", plaintTitle: "Division", ex: "÷", css: "card-counter success" },
    { url: "/mathmultiplicationtable", title: "Multiplication Table", plaintTitle: "Multiplication Table", ex: "▦", css: "card-counter primary" },
    { url: "/mathbasicfraction", title: "Basic Fractions", plaintTitle: "Basic Fractions", ex: "½ ⅓", css: "card-counter success" },
    { url: "/mathclock", title: "Telling Time", plaintTitle: "Telling Time", ex: "9:35:03", css: "card-counter primary" },
]